general {
    no_fade_in = false
}

background {
    monitor =
    path = ~/Pictures/wallpapers/p3.jpg
    blur_passes = 1
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    outer_color = rgb(0a0a0a)
    inner_color = rgb(255, 255, 255)
}